repos:
- hooks:
  - args:
    - --line-length=79
    id: black
  repo: https://github.com/psf/black
  rev: 22.10.0
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
    language_version: python3
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: reorder-python-imports
  repo: https://github.com/asottile/reorder_python_imports
  rev: v3.8.5
- hooks:
  - args:
    - --py39-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.1.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.35.0
